### ISSUE TITLE
"Other" files do not trigger compilation fail

### ISSUE THREAD

**Issue by bcardarella** [alexspeller/ember-twiddle#18]
To reproduce

* Add Other File
* Name "services/foo.js"
* Add bad javascript to the file
* Build system is never triggered or it is not reporting errors

**Comment by joostdevries** [comment]
@bcardarella correct. they're lazily imported (once you use the file it should trigger errors).. Will have to look into that..

**Comment by joostdevries** [comment]
@bcardarella This was closed in #24

**Comment by bcardarella** [comment]
:+1:
