### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by masciugo** [alexspeller/ember-twiddle#25]
![ember-twiddle-bug](https://cloud.githubusercontent.com/assets/454321/8311448/94f572f4-19d6-11e5-884d-3d4e3535fd30.gif)

ps.: thanks for this amazing tool

**Comment by alexspeller** [comment]
Updated readme, see https://github.com/alexspeller/ember-twiddle/commit/bb634bdacd7758026dcfce820c6341446249c8f0
