### ISSUE TITLE
How to ES6 import?

### ISSUE THREAD

**Issue by Gaurav0** [alexspeller/ember-twiddle#28]
See http://twiddle.joostdvrs.com/1c0da49ac7eab2af3d77

In the console, I get the error message: Could not find module views/view-stack

The module views/view-stack.js exists, what is the correct path by which I can import it?

I have tried:

    import ViewStack from "views/view-stack";

    import ViewStack from "./views/view-stack";

    import ViewStack from "../views/view-stack";

    import ViewStack from "app/views/view-stack";

**Comment by joostdevries** [comment]
I have to look into this a little closer. I'm working on a next iteration which drastically changes how modules are resolved.

**Comment by joostdevries** [comment]
@Gaurav0 currently, your app is called `demo-app`, so lookups need to happen on that path. I've got an issue open to fix that #41.

**Comment by Gaurav0** [comment]
@joostdevries Relative imports are working though, so the user doesn't really need to know the app name. http://ember-twiddle.com/04afc25368d924967979
